<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Image extends Model
{
    protected $table = "images";
    protected $fillable = ['path' ,'filename'];
    protected function getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }
    protected function asDateTime($value)
    {
        return $value; // TODO: Change the autogenerated stub
    }
}
























